### ISSUE TITLE
Idea: create a DSL

### ISSUE THREAD

**Issue by markphelps** [get-glu/glu#132]
Currently, setting up deployment pipelines in Glu requires end users to write Go code. While this provides flexibility and integrates seamlessly with Go-based ecosystems, it creates potential barriers for users who are unfamiliar with Go or who prefer more declarative and streamlined configurations.

This issue proposes exploring the creation of a Domain-Specific Language (DSL) for Glu as an alternative to directly writing Go code.

Re: https://manifesto.getglu.dev/#dynamic-flexible-pipelines

Some of the feedback we have gotten around the manifesto and impl of Glu includes (summarized):

> While pipelines often benefit from the flexibility of real code (e.g., loops, conditionals, runtime logic), the majority of pipeline definitions don't require this level of complexity. Instead, the occasional need for advanced logic could be handled with escape hatches into a full-powered language like Go. Commenters noted that using real code can make pipelines harder to interpret without execution, suggesting that a DSL with limited power but better interpretability might strike a balance between usability and flexibility.

## Example DSL

Taking our [gitops example](https://github.com/get-glu/gitops-example/blob/main/cmd/pipeline/main.go) and creating a strawman DSL could look like:

```
system "gitops-example" {
    pipeline "gitops-example-app" {
        source "oci" {
            type "oci"
            name "app"
        }

        source "git" {
            type "git"
            name "gitopsexample"
        }

        phase "oci" {
            source "oci"
        }

        phase "staging" {
            source "git"
            promotes_from "oci"
            labels {
                "url" = "http://0.0.0.0:30081"
            }
        }

        phase "production" {
            source "git"
            promotes_from "staging"
            labels {
                "url" = "http://0.0.0.0:30082"
            }
        }

        trigger "schedule" {
            interval "10s"
            matches_label "env", "staging"
        }
    }
}
```

This would remove much of the boilerplate required to implement the same pipeline in Go.

We could use a tool like [antlr](https://github.com/antlr/antlr4) to generate the lexer/parser code and adapt it to the glu runtime.

## TODO

The above example leaves out a large part of Glu which is how could we 'describe' custom resources? Ie the app resource in the Glu GitOps example which 'knows' how to source itself from a file in a Git repository as well as write back it's updated state to that file?

**Comment by markphelps** [comment]
FYI I added the RFC label because we're hoping for feedback. I'm not 💯 that we actually want a DSL or if we want to stick to Go / other languages. There are pros and cons to both. But I did want to put this out there incase anyone has strong feelings one way or the other.

**Comment by PythonHacker24** [comment]
I'm adding my opinion: Why do we need a DSL? Can we work with YAML or JSON to fire it up? 

A custom DSL adds friction to adopting it and requires frequent lookups to the docs for syntax errors. Also, YAML and JSON have LSPs in editors, which makes them better at syntax and linter support (also, they are accepted standards).

Deployment as code is cool with Golang, but adding a YAML or JSON support makes it even better (or, say, DSL if needed)  by adding one more option. But again, other tools like Terraform support YAML-based deployments; this feature will be an addition to Glu as feature support, not as a novelty, which Deployment as Code is providing.

**Comment by markphelps** [comment]
@PythonHacker24 sorry for the delay in responding! Thank you for your feedback. I think I agree after some introspection, we should start as simple as possible by using something like YAML/JSON to describe the graph instead of a bespoke DSL that users would have to learn.

We are thinking that perhaps where Glu could be most valuable in the short term is to be an observability tool allowing users to inspect their already existing pipelines instead of requiring them to rebuild those pipelines in Go. Even if we decide to abandon the parts of Glu that do the promotion/rollback for now, having a configuration to describe the pipeline graph would still be required to draw the boxes in the UI. WDYT?

**Comment by markphelps** [comment]
YAML example:

```yaml
pipeline:
  name: gitops-example-app
  sources:
    git:
      type: ci
      scm: github
      name: get-glu/gitops-example
    
    staging-k8s:
      type: kubernetes
      name: staging
      config:
        namespace: staging
        name: gitops-example-app
        container: gitops-example-app
    
    production-k8s:
      type: kubernetes
      name: production
      config:
        namespace: production
        name: gitops-example-app
        container: gitops-example-app
    
    oci:
      type: oci
      name: app

  phases:
    ci:
      source: ci
    
    oci:
      source: oci
      depends_on: ci
    
    staging:
      source: staging-k8s
      depends_on: oci
      labels:
        url: http://0.0.0.0:30081
    
    production:
      source: production-k8s
      depends_on: staging
      labels:
        url: http://0.0.0.0:30082
```
